name: Test
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Setup steamcmd
        uses: CyberAndrii/setup-steamcmd@v1
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - run: bash ./scripts/install_pz.sh
      - run: bash ./scripts/prep_libs.sh
      - run: gradle run --args "cli --out ./java-types"
